// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAb9OWzaRg0mOmvbySFVFecHQ9J5_EG4vo',
    appId: '1:496638349075:android:1e97e98eba565005c394e6',
    messagingSenderId: '496638349075',
    projectId: 'dopeshield-fa348',
    databaseURL: 'https://dopeshield-fa348-default-rtdb.firebaseio.com',
    storageBucket: 'dopeshield-fa348.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFaDKdfr6xJM9RlrVuIJu8DmczcLrAADU',
    appId: '1:496638349075:ios:bd1e439bc34e1b70c394e6',
    messagingSenderId: '496638349075',
    projectId: 'dopeshield-fa348',
    databaseURL: 'https://dopeshield-fa348-default-rtdb.firebaseio.com',
    storageBucket: 'dopeshield-fa348.firebasestorage.app',
    iosBundleId: 'com.example.dopeshield',
  );

}